FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# OnePizza API 1.0

This document is outdated.  Please refer to the below document

Language   |  URL
-----------|-----------------------------------
English    | [https://onepizzav1english.docs.apiary.io/](https://onepizzav1english.docs.apiary.io/)
中文       | [https://onepizzav1chinese.docs.apiary.io/](https://onepizzav1chinese.docs.apiary.io/)