FORMAT: 1A
HOST: https://api.sandbox.onepizza.net/

# Less'More API

- 沙箱环境地址: [https://api.sandbox.onepizza.net](https://api.sandbox.onepizza.net)
- 正式环境地址：[https://api.onepizza.net](https://api.onepizza.net)
- Swagger: [https://api.sandbox.onepizza.net/swagger/index.html](https://api.sandbox.onepizza.net/swagger/index.html)

### 服务器响应码

- 200 Ok            服务器已成功处理了请求
- 400 BadRequest    客户端提交的数据错误
- 401 Unauthorized  请求要求身份验证
- 500 Server Error  服务器遇到错误，无法完成请求

### 常用参数说明

1. 国家编码请参照 [ISO-3166-1 Alpha 2 Country Code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)
    > 例如: `CN`, `US`

2. 币别请参照 [Currency code](https://en.wikipedia.org/wiki/ISO_4217)
    > 目前系统支持的币别: 
    > `USD`, `CNY`, `EUR`, `GBP`, `CAD`, `JPY`, `KRW`, `AUD`, `HKD`, `MYR`, `TWD`

3. 时间格式 `yyyy-MM-ddTHH:mm:ss`
    > 例如: `2019-04-22T08:07:11` 默认时区是UTC  
    > 如果要指定时区 比如中国(UTC+8): `2019-04-22T08:07:11+08:00`  

4. 重量
    > 支持的重量单位: `G`, `KG`, `LB`, `OZ`

5. 长度
    > 支持的长度单位: `CM`, `IN`, `MM`

6. 机场编码
    > 三字码, 例如: `SHZ`, `HKG`, `SHA`, `JFK`, `LAX`

7. 清关方式
    > `Regular321`, `Enhanced321`, `Selfclearence`

### 工作流程
1. 创建包裹
2. 创建入网清单(推送入网)
3. 创建出库清单
4. 确认登机 

# Data Structures

## parcel
+ orderNbr: `87352121663001` (string, required) - 订单号
+ consignee (contact, required) - 收件人信息
+ shipper (contact, required) - 寄件人信息
+ lineInfos (array[lineInfo], required) - 申报信息
+ weight (weight, required) - 重量信息
+ dimension (dimension) - 三维信息
+ idCardNbr (string) - 身份证号码
+ distInfo (string) - 分拨信息, 此信息会显示到 label 上
+ pickingInfos (array[string]) - 分拣信息， 最多四条信息， 每条最大17位, 此信息会显示到 label 上

## contact
+ name: `James Charles` (string, required) - 姓名，姓与名之间必须空格
+ phone: `123-456-7890` (string) - 手机号
+ email: `somebody@olabala.com` (string) - 邮箱
+ company: `Less'More Ltd` (string) - 公司
+ street1: `12345 Business Oneway` (string, required) - 详细地址1
+ street2 (string) - 详细地址2
+ street3 (string) - 详细地址3
+ district (string) - 区
+ city: `City Of Industry` (string, required) - 城市
+ province: `CA` (string, required) - 省份/州
+ postalCode: `91789` (string, required) - 邮编
+ countryCode: `US` (string, required) - 国家代码

## lineInfo
+ goodsInfo (goodsInfo, required) - 商品信息
+ lineTotal (money, required) - 包裹**总价值**
+ quantity: `4` (number, required) - 包裹中物品总数, 值在: 1 ~ 255

## goodsInfo
+ name: `Macbook Pro` (string, required) - 商品名称
+ localName: `苹果笔记本电脑` (string) - 商品本地名称, 根据国家来定, 如果是中国, 就是中文
+ sku: `132453301` (string) - 商品SKU
+ spec: `13Inch, TouchBar` (string) - 商品规格
+ brand: `Apple` (string) - 商品品牌
+ model: `MR942CH/A` (string) - 商品型号
+ hsCode: `165390` (string) - HS Code

## money
+ value: `100.2` (number, required) - 价值, 值在: 0.11 ~ 800.00 USD
+ unit: `USD` (string, required) - 价值单位

## weight
+ value: `22.1` (number, required) - 重量值 < 70 LB
+ unit: `LB` (string, required) - 重量单位

## dimension
+ length: `102.1` (number) - 长, 值在: 1 ~ 999.00 CM
+ width: `102.1` (number) - 宽, 值在: 1 ~ 999.00 CM
+ height: `102.1` (number) - 高, 值在: 1 ~ 999.00 CM
+ unit: `CM` (string, required) - 单位

## sack
+ sackNbr: `abc12345678` (string, required) - 袋子编号
+ parcels (array[sackParcel], required) - 包裹信息

## sackParcel
+ trackingNbr: `13421345644001` (string, required) - 运单号

## Token [/Tokens]

### 获取Token [POST]

+ Request (application/x-www-form-urlencoded)

    + Body
    
            username=demo&password=Pass123%24

+ Response 200 (application/json)

    + Body
    
            {
                "expires_in":2592000,
                "token_type":"Bearer",
                "access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5hbnQiOiIxMDAwMlx0LVx0MTAwMDFcdC1cdDEwMDAwXHQtXHRPUC0xMDAwMiAoQWRtaW4pXHReXHQxMDEsMTM1IiwibmJmIjoxNTU1OTI1MzQ3LCJleHAiOjE1NTg1MTczNDcsImlhdCI6MTU1NTkyNTM0NywiaXNzIjoibXlJc3N1ZXIiLCJhdWQiOiJ3ZWJzZXJ2aWNlIn0.pgGRW9v9gldOcLr8d16DYXFkdf3azTRT27oF_G9M8F8"
            }

## 包裹 [/Parcels]

### 创建包裹 [POST]

+ Request (application/json)
    + Headers

            Authorization: Bearer <Put Your Token Here>

    + Attributes
        + serviceCode: `CN-US-Express` (string, required) - 服务代码
        + parcels (array[parcel], required) - 包裹信息
    
    + Body

            {
                "serviceCode": "CN-US-Express",
                "parcels": [
                    {
                        "idCardNbr": "322321198912092341",
                        "orderNbr": "87352121663001",
                        "weight": {
                            "value": 700,
                            "unit": "G"
                        },
                        "dimension": {
                            "length": 50,
                            "width": 60,
                            "height": 40,
                            "unit": "CM"
                        },
                        "consignee": {
                            "name": "James Charles",
                            "phone": "123-456-7890",
                            "email": null,
                            "company": null,
                            "street1": "12345 Business Oneway",
                            "street2": null,
                            "street3": null,
                            "district": null,
                            "city": "City Of Industry",
                            "province": "CA",
                            "postalCode": "91789",
                            "countryCode": "US"
                        },
                        "shipper": {
                            "name": "Tao jun",
                            "phone": "13810221111",
                            "email": null,
                            "company": null,
                            "street1": "RM 101, No. 123 Pingxing Rd",
                            "street2": null,
                            "street3": null,
                            "district": "JingAn District",
                            "city": "Shanghai",
                            "province": "Shanghai",
                            "postalCode": "200040",
                            "countryCode": "CN"
                        },
                        "lineInfos": [
                            {
                            "goodsInfo": {
                                "sku": "132453301",
                                "spec": "13Inch, TouchBar",
                                "name": "Macbook Pro",
                                "localName": "苹果笔记本电脑",
                                "brand": "Apple",
                                "model": "MR942CH/A",
                                "hsCode": "165390"
                            },
                            "lineTotal": {
                                "value": 400,
                                "unit": "USD"
                            },
                            "quantity": 1
                            },
                            {
                            "goodsInfo": {
                                "sku": null,
                                "spec": null,
                                "name": "Mens T-Shirt",
                                "localName": "男士T恤衫",
                                "brand": "Uniqlo",
                                "model": "413744",
                                "hsCode": "225311"
                            },
                            "lineTotal": {
                                "value": 100,
                                "unit": "USD"
                            },
                            "quantity": 10
                            }
                        ],
                        "distInfo":"123-3212-321",
                        "pickingInfos":["SKU1 * 2", "SKU2 * 2"]
                        }
                    ]
            }

+ Response 200 (application/json)

        {
            "result": [
                {
                "orderNbr": "87352121663001",
                "trackingNbr": "9261342243522212341001",
                "barcodeNbr": "420957819261342243522212341001"
                "errors": []
                }
            ],
            "message": "",
            "isSuccess": true,
            "utcStamp": "2019-04-22T11:36:07.8782103Z"
        }

### 获取面单 [GET /Parcels/Label/{trackingNbr}]

+ Parameters
    + trackingNbr (required, string, `890232412001`) ... Tracking Number (`trackingNbr`)

+ Request (application/json)

    + Headers

            Authorization: Bearer <Put Your Token Here>

+ Response 200 (application/json)

        {
            "result": {
                "trackingNbr": "9274800000000000842749",
                "labelUrl": "http://label.onepizza.net/0?token=YXBwSWQ9MTIzJm5vbmNlPSZ0aW1lU3RhbXA9MTU1ODE4MjAyOQ.SW92TWZ4RkJ1S3RFYXU3YU0yOWFFUmZMU3FtcHBmZ0pCUmcwQjFiU0pxbz0"
            },
            "message": "",
            "isSuccess": true,
            "utcStamp": "2019-04-22T10:56:56.5523838Z"
        }

### 获取物流信息 [GET /Parcels/Tracking/{trackingNbr}]

+ Parameters
    + trackingNbr (required, string, `9274800000000000842749`) ... Tracking Number (`trackingNbr`)

+ Request (application/json)

    + Headers

            Authorization: Bearer <Put Your Token Here>

+ Response 200 (application/json)

        {
            "result": {
                "trackingNbr": "9274800000000000842749",
                "events": [
                    {
                        "place": "City of Industry, CA",
                        "stage": "Outgated",
                        "operator": "OP-107",
                        "operatedOn": "2019-04-23T09:10:14.355Z"
                    },
                    {
                        "place": "City of Industry, CA",
                        "stage": "Arrived",
                        "operator": "OP-102",
                        "operatedOn": "2019-04-21T04:10:01.221Z"
                    }
                ]
            },
            "message": "",
            "isSuccess": true,
            "utcStamp": "2019-04-22T10:59:58.0244672Z"
        }

## 测量 [/Measures]

### 更新重量 [PUT]

+ Request (application/json)

    + Headers

            Authorization: Bearer <Put Your Token Here>
    
    + Attributes
        + trackingNbr: `13421345644001` (string, required) - 运单号
        + weight (weight, required) - 重量信息
        + dimension (dimension) - 三维信息
    
    + Body
    
            [
                {
                    "trackingNbr": "13421345644001",
                    "weight": {
                        "value": 600,
                        "unit": "G"
                    },
                    "dimension": {
                        "length": 60,
                        "width": 70,
                        "height": 50,
                        "unit": "CM"
                    }
                },
                {
                    "trackingNbr": "13421345644002",
                    "weight": {
                        "value": 601,
                        "unit": "G"
                    },
                    "dimension": {
                        "length": 61,
                        "width": 71,
                        "height": 51,
                        "unit": "CM"
                    }
                }
            ]

+ Response 200 (application/json)

        {
            "result": [
                {
                    "trackingNbr": "13421345644001",
                    "newTrackingNbr": "983345637200000002",
                    "newBarcodeNbr": "420957819261342243522212341002",
                    "errors": []
                },
                {
                    "trackingNbr": "13421345644002",
                    "newTrackingNbr": "",
                    "newBarcodeNbr": "",
                    "errors": ["没找到包裹"]
                }
            ],
            "message": "",
            "isSuccess": true,
            "utcStamp": "2019-04-22T09:51:28.0773804Z"
        }

## 入网清单 [/LastMilerManifests]

### 推送入网 [POST]

+ Request (application/json)

    + Headers

            Authorization: Bearer <Put Your Token Here>

    + Attributes
        + trackingNbr: `13421345644001` (string, required) - 运单号
        + weight (weight, required) - 重量信息
    
    + Body

            [
                {
                    "trackingNbr": "342187643001",
                    "weight": {
                        "value": 200,
                        "unit": "G"
                    }
                },
                {
                    "trackingNbr": "342187643002",
                    "weight": {
                        "value": 300,
                        "unit": "G"
                    }
                },
                {
                    "trackingNbr": "342187643003",
                    "weight": {
                        "value": 400,
                        "unit": "G"
                    }
                }
            ]

+ Response 200 (application/json)

        {
            "result": [
                {
                    "trackingNbr": "342187643001",
                    "errors": []
                },
                {
                    "trackingNbr": "342187643002",
                    "errors": []
                },
                {
                    "trackingNbr": "342187643003",
                    "errors": []
                }
            ],
            "message": "",
            "isSuccess": true,
            "utcStamp": "2019-04-22T09:59:19.129116Z"
        }

## 出库清单 [/SackManifests]

### 创建出库清单 [POST]

+ Request (application/json)

    + Headers

            Authorization: Bearer <Put Your Token Here>

    + Attributes
        + sacks (array[sack], required) - 袋子信息
        + outgatedOn: `2019-04-28T19:04:02.921844+08:00` (string, required) - 出库时间
    
    + Body
    
            {
                "sacks":[
                    {
                        "sackNbr": "3421001",
                        "parcels": [
                        {
                            "trackingNbr": "129856001"
                        },
                        {
                            "trackingNbr": "129856002"
                        },
                        {
                            "trackingNbr": "129856003"
                        }
                        ]
                    },
                    {
                        "sackNbr": "3421002",
                        "parcels": [
                        {
                            "trackingNbr": "229856001"
                        },
                        {
                            "trackingNbr": "229856002"
                        }
                        ]
                    }
                ],
                "outgatedOn": "2019-04-28T19:04:02.921844+08:00"
            }

+ Response 200 (application/json)

        {
        "result": {
            "sackManifestNbr": "Sackmft165000071"
        },
        "message": "",
        "isSuccess": true,
        "utcStamp": "2019-04-22T10:31:24.297503Z"
        }

### 确认登机 [PUT /SackManifests/Flight/{sackManifestNbr}]

+ Parameters
    + sackManifestNbr: `763251001` (string, required) - 出库清单编号

+ Request (application/json)
    + Headers

            Authorization: Bearer <Put Your Token Here>

    + Attributes
        + sackManifestNbr: `21392001` (string, required) - 出库清单号
        + poa: `LAX` (string, required) - 目的港
        + pod: `HKG` (string, required) - 始发港
        + mawbNbr: `123-45678900` (string, required) - 航空主提单号
        + flightNbr: `f123` (string, required) - 航班号
        + eta: `2019-04-24T22:10:33Z` (string, required) - 预计抵港时间
        + etd: `2019-04-23T23:10:33Z` (string, required) - 预计离港时间
        + boardedOn: `2019-04-23T22:10:33Z` (string, required) - 登机时间
        + boardedOn: `2019-04-23T22:10:33Z` (string, required) - 登机时间
        + clrMethod: `Regular321` (string) - 清关方式, 详细请参照上面的清关方式说明
    + Body
    
            {
                "poa": "LAX",
                "pod": "HKG",
                "mawbNbr": "3213401",
                "flightNbr": "f1231",
                "eta": "2019-04-25T17:39:49.5865488+08:00",
                "etd": "2019-04-23T17:39:49.58655+08:00",
                "boardedOn": "2019-04-22T17:39:49.5865214+08:00",
                "clrMethod": "Regular321"
            }

+ Response 200 (application/json)

        {
            "result": {
                "sackManifestNbr": "111111111"
            },
            "message": "",
            "isSuccess": true,
            "utcStamp": "2019-04-22T10:42:34.5216559Z"
        }